# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be128e97c03d0ed1acc854022633c7b10435ed1f741cdf6a29ae38c0b4df494ddc7a29d6b15a2443e02364b05b1481b53d9dfee64e8e0bab59035c14b9ddd92b

test:
  secret_key_base: 1b5210df5bac9be39048e586b4a66e64218a7d3f40434c88428171336683736deb4c34779a5d3801b741e420b1ed7d9afc7933eeb22c82b9a11166d4c939164c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
